# Section A: Level 1 Questions
#1.	Read the data from all the tables

select * from supplier;
select * from product;
select * from orderitem;
select * from orders;
select * from customer;

#2.	Find the country-wise count of customers.

select country,count(id) as count_cust from customer group by country order by count_cust desc;

#3.	Display the products that are not discontinued. 

select * from product where isdisconinued='1';

#4.	Display the list of companies along with the product name that they are supplying. 

select s.companyname,p.productname from supplier s join product p on s.id=p.supplierid;

#5.	Display customer information about who stays in 'Mexico'

select * from customer where country='Mexico';

#Additional: Level 1 questions


#6.	Display the costliest item that is ordered by the customer.
  select c.id as customer_id,p.productname,p.unitprice from 
  customer c join orders o on c.id=o.customerid
  join orderitem oi on o.id=oi.orderid
  join product p on p.id=oi.productid
  where (c.id,p.unitprice) in
  (select c.id,max(p.unitprice) from product p 
  join orderitem oi on oi.productid=p.id
  join orders o on o.id=oi.orderid
  join customer c on o.customerid=c.id
  group by c.id);

#7.	Display supplier ID who owns the highest number of products.
  with max_p as (
  select s.id,count(p.id) as cnt_prod
  from supplier s join product p on p.supplierid=s.id 
  group by s.id)
  select * from max_p where cnt_prod in 
  (select max(cnt_prod) from max_p);

#8.	Display month-wise and year-wise counts of the orders placed.
  select year(orderdate) as year,month(orderdate) as month,count(id) as order_count from orders 
  group by year(orderdate),month(orderdate) order by year asc,month asc;

#9.	Which country has the maximum number of suppliers?
  with max_c as(
  select country,count(id)over(partition by country) as count 
  from supplier
  )
  select distinct * from max_c where count in 
  (select max(count) from max_c);

#10.	Which customers did not place any orders?
  select * from customer
  where id not in
  (select customerid from orders); 

#Section B: Level 2 Questions:

#1.	Arrange the Product ID and Name based on the high demand by the customer.
  select p.id as product_id, p.productname, sum(oi.quantity) total_quantity
  from orderitem oi join product p on p.id=oi.productid 
  group by p.id,p.productname order by total_quantity desc;

#2.	Display the total number of orders delivered every year
  select year(orderdate) as year,count(id) as total_orders from orders group by year(orderdate);

#3.	Calculate year-wise total revenue. 
  select year(orderdate) as year,sum(totalamount) as total_orders from orders group by year(orderdate);

#4.	Display the customer details whose order amount is maximum including his past orders. 
  select c.*,sum(totalamount) as total_order_amount from customer c 
  join orders o on o.customerid=c.id
  group by c.id order by sum(totalamount) desc limit 1;

#5.	Display the total amount ordered by each customer from high to low.
  select c.*,sum(totalamount) as total_order_amount from customer c 
  join orders o on o.customerid=c.id
  group by c.id order by sum(totalamount) desc;

#Additional Level 2 Questions:

#The sales and marketing department of this company wants to find out how frequently customers do business with them. 
# (Answer Q 6 for the same) 
#6.	Approach - List the current and previous order dates for each customer.
  select c.id as customerid,c.firstname,o.orderdate
  from customer c join orders o on o.customerid=c.id
  order by customerid,orderdate;

#7.	 Find out the top 3 suppliers in terms of revenue generated by their products. 
  select s.id as supplierid,s.contactname,sum(quantity*oi.unitprice) as totalrevenue 
  from supplier s 
  join product p on s.id=p.supplierid
  join orderitem oi on oi.productid=p.id
  join orders o on o.id=oi.orderid
  group by s.id,s.contactname order by totalrevenue desc;

#8.	Display the latest order date (should not be the same as the first order date) of all the customers with customer details. 
  select c.*,min(orderdate) 
  from customer c 
  join orders o on o.CustomerId=c.id
  group by c.id;

#9.	Display the product name and supplier name for each order  
  select oi.orderid,p.productname,s.contactname as suppliername 
  from supplier s join product p on p.supplierid=s.id 
  join orderitem oi on oi.productid=p.id
  join orders o on o.id=oi.orderid;

#Section C: Level 3 Questions:

#1.	Fetch the customer details who ordered more than 10 products in a single order.
  with product_orderd as(
  select distinct c.*,count(o.id)over(partition by c.id) as count 
  from customer c join orders o on o.customerid=c.id)
  select * from product_orderd where count>10 order by count desc;

#2.	Display all the product details with the ordered quantity size as 1. 
  select p.* from product p join orderitem oi on oi.productid=p.id where quantity =1;

#3.	Display the companies that supply products whose cost is above 100.
  select distinct s.* from supplier s join product p on p.SupplierId=s.id
  join orderitem oi on oi.productid=p.id where oi.unitprice>100;

#4.	Create a combined list to display customers and supplier lists as per the below format.
-- skip this question as the question is not complete
#5.	Display the customer list who belongs to the same city and country arranged country-wise
  select distinct c1.id,c1.firstname,c2.FirstName,c1.city,c1.country 
  from customer c1 join customer c2 on (c1.city,c1.country)=(c2.city,c2.country) 
  where c1.id<>c2.id
  order by c1.country;

#Section D: Level 4 Questions:
  
#1.	The company sells the products at different discount rates. Refer actual product price in the product table and the selling price 
#in the order item table. Write a query to find out the total amount saved in each order then 
#display the orders from highest to lowest amount saved. 
  select oi.orderid,sum((p.unitprice-oi.unitprice)*oi.quantity) as total_amount_saved  
  from product p join orderitem oi on p.id=oi.productid 
  group by oi.orderid order by total_amount_saved desc;

#2.	Mr. Kavin wants to become a supplier. He got the database of "Richard's Supply" for reference. Help him to pick: 
#a.	List a few products that he should choose based on demand.
#b.	Who will be the competitors for him for the products suggested in the above questions? 
  select distinct s.contactname, p.productname
  from orderitem oi join product p on p.id=oi.productid 
  join supplier s on p.supplierid=s.id
  group by p.id,p.productname,s.contactname having sum(oi.quantity)>1000
  order by s.contactname;

#3.	Create a combined list to display customers' and suppliers' details considering the following criteria 
#a.	Both customer and supplier belong to the same country 
#b.	Customers who do not have a supplier in their country
#c.	A supplier who does not have customers in their country 
  select c.*,s.* from customer c
  join supplier s on s.country=c.country
  union all
  select c.*,s.* from customer c
  left join supplier s on s.country=c.country 
  where s.country is null
  union all 
  select * from customer c
  right join supplier s on s.country=c.country 
  where c.country is null;

#4.	Find out for which products, the UK is dependent on other countries for the supply. 
# List the countries which are supplying these products in the same list.
  select distinct c.country as UK,s.country as import_from,p.productname 
  from customer c join supplier s on s.country<>c.country
  join product p on p.supplierid=s.id
  where c.country='uk';
